language: ruby
rvm:
 - 2.1
before_install:
 - wget http://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.2.1/swagger-codegen-cli-2.2.1.jar -O ./swagger-codegen-cli.jar

script:
 - bundle exec jekyll build
 - java -jar swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l php -o ._site/clients/php
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAIXSAFTOMITJARX5Q
  secret_access_key:
    secure: NHzGo+INsKueUTiVadMQKpqcUqjVyrikF+1bNAFUyUhskcLXwC4KKdU+aY2DDkj0iAV2056P17D/H4Fmm0sl0dml9s1iSq7Dn6RiUYF4hVu32AVnGP3hOeZ5aCPRYhzs8ciaEg9QcEnOx6568HWccRIFrqXabaUgooZSfT16Eu8qhzu1Ipw11sW7K9iKPmd1TkZiSAQxXyXG70UktPvNrxMKt0U4Tg0ZE9wkn2Qv/jIhIwl4zqfginPi47E7X/4mLd/t0R/j1UN5L0g//EpXfnMXDUCSJ2b5wgK0AvR83B7a39yA9CBmde3izi/Sfbby3yTgXRgj7xAmsv4cHnYNhvVHuZiJJ0oDNj+MXxFSpxaQ0E1/MohGhd3+t2zqIIk3eS6borCxbIE+qbpRJI3tsAb/MgUUfnJkjfuq2Ez8IlBcx+xws40Ug2EPImVnDwLWhFf6/TePGqQb0HM/WYqDscaut14tm0Hu/c5KqJlBUk3VwiRIkmTt6t3/YQZO8EjhjcpAoXBpcpjAEusbkRh7RpBR3e6LhzRstuiDU2NLQ6leTSWxqykCRQeH+USwV0XnBaJRJXHiEnpiOaW32z31kxHAaiflZfuK2+I/iZL53rxkGUoD8ghQs2xJjAPDb/4FBk9Uaa/58oLlyZY370bt2ZBX0uy4C5b+lrMp1T1b7UM=
  bucket: developer.bombbomb.com
  local-dir: _site
  acl: public_read
  on:
    repo: bombbomb/developer.bombbomb.com
