# Site settings
title: BombBomb Developer
email: support@bombbomb.com
url: https://www.bombbomb.com
description: "Add the power of video into your platform with BombBomb's API and Libraries"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/bombbomb/
  - title: facebook
    url: https://www.facebook.com/BombBomb
  - title: github
    url: https://github.com/bombbomb

# Build settings
markdown: kramdown
permalink: pretty

exclude: [vendor]